export const letsellr = {
  contactNumber: "9402384",
};

export const categories = [
  {
    title: "PGs/Hostels",
    description: "Affordable paying guest accommodations with all amenities for students and working professionals.",
    count: "1,200+",
    image: "/images/category-card-big-sm.png",
    action: "/category/pg-hotels",
  },
  {
    title: "House/Villa's",
    description: "Fully furnished and semi-furnished apartments for individuals and families.",
    count: "850+",
    action: "/category/house-villas",
  },
  {
    title: "Flat/Apartments",
    description: "Budget-friendly hostel stays near educational institutions and IT hubs.",
    image: "/images/category-card-room-1.png",
    count: "320+",
    action: "/category/flat-apartments",
  },
  {
    title: "Commercial",
    description: "Independent houses with complete privacy and flexibility.",
    image: "/images/category-card-room-2.png",
    count: "180+",
    action: "/category/commercial",
  },
  {
    title: "Land",
    description: "Independent houses with complete privacy and flexibility.",
    image: "/images/category-card-land.png",
    count: "180+",
    action: "/category/land",
  },
];

export const sampleProperties = [
  {
    _id: "1",
    title: "Modern 2BHK Apartment in Kochi",
    description: "A stylish 2-bedroom apartment with balcony views of the city, located near Infopark.",
    images: [
      "https://picsum.photos/seed/kochi1/800/500",
      "https://picsum.photos/seed/kochi2/800/500",
      "https://picsum.photos/seed/kochi3/800/500",
      "https://picsum.photos/seed/kochi4/800/500",
      "https://picsum.photos/seed/kochi5/800/500",
    ],
    category: { _id: "c1", name: "Apartment" },
    amenity: "WiFi, Air Conditioning, Parking",
    price: 18000,
    location: {
      name: "Kakkanad, Kochi",
      url: "https://www.google.com/maps?q=Kakkanad,+Kochi&output=embed",
    },
    rating: 3,
    priceOptions: [
      {
        price: 8000,
        description: "with food",
      },
    ],
    contactNumber: "23234927349",
  },
  {
    _id: "2",
    title: "Cozy Studio Flat near Marine Drive",
    description: "Compact studio apartment ideal for bachelors or working professionals.",
    images: [
      "https://picsum.photos/seed/marine1/800/500",
      "https://picsum.photos/seed/marine2/800/500",
      "https://picsum.photos/seed/marine3/800/500",
      "https://picsum.photos/seed/marine4/800/500",
      "https://picsum.photos/seed/marine5/800/500",
    ],
    category: { _id: "c2", name: "Studio" },
    amenity: "Furnished, 24x7 Water, CCTV",
    price: 12000,
    location: {
      name: "Marine Drive, Kochi",
      url: "https://www.google.com/maps?q=Marine+Drive,+Kochi&output=embed",
    },
    rating: 5,
  },
  {
    _id: "3",
    title: "Luxury Villa with Private Garden",
    description: "Spacious 4BHK villa featuring a private garden and modern kitchen, perfect for families.",
    images: [
      "https://picsum.photos/seed/villa1/800/500",
      "https://picsum.photos/seed/villa2/800/500",
      "https://picsum.photos/seed/villa3/800/500",
      "https://picsum.photos/seed/villa4/800/500",
      "https://picsum.photos/seed/villa5/800/500",
    ],
    category: { _id: "c3", name: "Villa" },
    amenity: "Garden, Modular Kitchen, Security",
    price: 65000,
    location: {
      name: "Panampilly Nagar, Kochi",
      url: "https://www.google.com/maps?q=Panampilly+Nagar,+Kochi&output=embed",
    },
    rating: 2,
  },
  {
    _id: "4",
    title: "1BHK Apartment near Metro Station",
    description: "Affordable 1BHK apartment just 5 minutes away from the nearest metro station.",
    images: [
      "https://picsum.photos/seed/metro1/800/500",
      "https://picsum.photos/seed/metro2/800/500",
      "https://picsum.photos/seed/metro3/800/500",
      "https://picsum.photos/seed/metro4/800/500",
      "https://picsum.photos/seed/metro5/800/500",
    ],
    category: { _id: "c1", name: "Apartment" },
    amenity: "Lift, Generator Backup, Security",
    price: 15000,
    location: {
      name: "Edappally, Kochi",
      url: "https://www.google.com/maps?q=Edappally,+Kochi&output=embed",
    },
    rating: 4,
  },
  {
    _id: "5",
    title: "Beachside Cottage with Sea View",
    description: "A peaceful cottage by the beach with stunning sunset views, perfect for remote workers.",
    images: [
      "https://picsum.photos/seed/beach1/800/500",
      "https://picsum.photos/seed/beach2/800/500",
      "https://picsum.photos/seed/beach3/800/500",
      "https://picsum.photos/seed/beach4/800/500",
      "https://picsum.photos/seed/beach5/800/500",
    ],
    category: { _id: "c4", name: "Cottage" },
    amenity: "Sea View, Kitchen, Parking",
    price: 28000,
    location: {
      name: "Cherai Beach, Kochi",
      url: "https://www.google.com/maps?q=Cherai+Beach,+Kochi&output=embed",
    },
    rating: 4.5,
  },
  {
    _id: "6",
    title: "Shared PG for Women",
    description: "Safe and affordable shared PG accommodation for women with meals included.",
    images: [
      "https://picsum.photos/seed/pg1/800/500",
      "https://picsum.photos/seed/pg2/800/500",
      "https://picsum.photos/seed/pg3/800/500",
      "https://picsum.photos/seed/pg4/800/500",
      "https://picsum.photos/seed/pg5/800/500",
    ],
    category: { _id: "c5", name: "PG" },
    amenity: "Meals, Laundry, CCTV Security",
    price: 9500,
    location: {
      name: "Kaloor, Kochi",
      url: "https://www.google.com/maps?q=Kaloor,+Kochi&output=embed",
    },
    rating: 3.5,
  },
  {
    _id: "7",
    title: "Luxury Penthouse with Terrace",
    description: "Top-floor penthouse with private terrace garden and panoramic city view.",
    images: [
      "https://picsum.photos/seed/penthouse1/800/500",
      "https://picsum.photos/seed/penthouse2/800/500",
      "https://picsum.photos/seed/penthouse3/800/500",
      "https://picsum.photos/seed/penthouse4/800/500",
      "https://picsum.photos/seed/penthouse5/800/500",
    ],
    category: { _id: "c6", name: "Penthouse" },
    amenity: "Terrace Garden, Smart Home, Lift",
    price: 75000,
    location: {
      name: "Vyttila, Kochi",
      url: "https://www.google.com/maps?q=Vyttila,+Kochi&output=embed",
    },
    rating: 4.7,
  },
  {
    _id: "8",
    title: "Compact Room for Rent",
    description: "Simple single room ideal for students or short stays, includes basic amenities.",
    images: [
      "https://picsum.photos/seed/room1/800/500",
      "https://picsum.photos/seed/room2/800/500",
      "https://picsum.photos/seed/room3/800/500",
      "https://picsum.photos/seed/room4/800/500",
      "https://picsum.photos/seed/room5/800/500",
    ],
    category: { _id: "c7", name: "Room" },
    amenity: "Bed, Fan, Shared Bathroom",
    price: 6000,
    location: {
      name: "Palarivattom, Kochi",
      url: "https://www.google.com/maps?q=Palarivattom,+Kochi&output=embed",
    },
    rating: 3.8,
  },
  {
    _id: "9",
    title: "3BHK Family Apartment with Balcony",
    description: "Spacious 3BHK apartment with balcony and covered parking space.",
    images: [
      "https://picsum.photos/seed/family1/800/500",
      "https://picsum.photos/seed/family2/800/500",
      "https://picsum.photos/seed/family3/800/500",
      "https://picsum.photos/seed/family4/800/500",
      "https://picsum.photos/seed/family5/800/500",
    ],
    category: { _id: "c1", name: "Apartment" },
    amenity: "Balcony, Parking, Lift",
    price: 30000,
    location: {
      name: "Elamkulam, Kochi",
      url: "https://www.google.com/maps?q=Elamkulam,+Kochi&output=embed",
    },
    rating: 4.2,
  },
  {
    _id: "10",
    title: "Student Hostel near College",
    description: "Budget-friendly hostel for students, close to major educational institutions.",
    images: [
      "https://picsum.photos/seed/hostel1/800/500",
      "https://picsum.photos/seed/hostel2/800/500",
      "https://picsum.photos/seed/hostel3/800/500",
      "https://picsum.photos/seed/hostel4/800/500",
      "https://picsum.photos/seed/hostel5/800/500",
    ],
    category: { _id: "c8", name: "Hostel" },
    amenity: "Mess, WiFi, Shared Study Area",
    price: 8000,
    location: {
      name: "Kalamassery, Kochi",
      url: "https://www.google.com/maps?q=Kalamassery,+Kochi&output=embed",
    },
    rating: 4,
  },
];
